[workspace]
members = [
  "clapgrep-core",
  "clapgrep-cosmic",
  "clapgrep-i18n",
  "ripgrep-all",
  "librusl",
]
resolver = "2"

[workspace.dependencies.i18n-embed]
version = "0.14"
features = ["fluent-system", "desktop-requester"]
