[workspace]
members = ["clapgrep-cosmic", "clapgrep-gtk", "clapgrep-i18n", "librusl"]
resolver = "2"

[workspace.dependencies.i18n-embed]
version = "0.14"
features = ["fluent-system", "desktop-requester"]
